default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

development:
  <<: *default
  database: penspinning_development


test:
  <<: *default
  database: penspinning_test


production:
  <<: *default
  database: penspinning_production
  username: penspinning
  password: <%= ENV['PENSPINNING_DATABASE_PASSWORD'] %>
