default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: penspinning_development


test:
  <<: *default
  database: penspinning_test


production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
  port: 3306
  # database: penspinning_production
  # username: penspinning
  # password: <%= ENV['PENSPINNING_DATABASE_PASSWORD'] %>
